package com.module.autographs.userpreferencesearch.microservice.util;

public class Constants {

    // HTTP STATUS CODES
    public static final String HTTP_RESPONSE_CODE_OK = "200";
    public static final String HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR = "500";

    // ALL API PATHS

    // 1 - NEW CAR REGISTRATIONS
    public static final String NEW_CAR_REGISTRATION_GET_API_PATH = "/getAllNewCarRegistrationsData";
    public static final String NEW_CAR_REGISTRATION_POST_API_PATH = "/addNewCarRegistrationsData";
    public static final String NEW_CAR_REGISTRATION_DELETE_ALL_API_PATH = "/deleteAllNewCarRegistrationsData";
    public static final String NEW_CAR_REGISTRATION_BY_QUERY_GET_API_PATH = "/getAllNewCarRegistrationsDataByQuery";

    // 2 - NEW CAR REGISTRATIONS BY FUEL TYPE
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_GET_API_PATH = "/getAllNewCarRegistrationsByFuelTypeData";
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_POST_API_PATH = "/addNewCarRegistrationsByFuelTypeData";
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_DELETE_ALL_API_PATH = "/deleteAllNewCarRegistrationsByFuelTypeData";

    // 3 - NEW CAR REGISTRATIONS BY SALES TYPE
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_GET_API_PATH = "/getAllNewCarRegistrationsBySalesTypeData";
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_POST_API_PATH = "/addNewCarRegistrationsBySalesTypeData";
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_DELETE_ALL_API_PATH = "/deleteAllNewCarRegistrationsBySalesTypeData";

    // 4 - NEW LCV REGISTRATIONS
    public static final String NEW_LCV_REGISTRATION_GET_API_PATH = "/getAllNewLCVRegistrationsData";
    public static final String NEW_LCV_REGISTRATION_POST_API_PATH = "/addNewLCVRegistrationsData";
    public static final String NEW_LCV_REGISTRATION_DELETE_ALL_API_PATH = "/deleteAllNewLCVRegistrationsData";

    // 5 - NEW LCV REGISTRATIONS BY FUEL TYPE
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_GET_API_PATH = "/getAllNewLCVRegistrationsByFuelTypeData";
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_POST_API_PATH = "/addNewLCVRegistrationsByFuelTypeData";
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_DELETE_ALL_API_PATH = "/deleteAllNewLCVRegistrationsByFuelTypeData";

    // 6 - NEW LCV REGISTRATIONS BY SALES TYPE
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_GET_API_PATH = "/getAllNewLCVRegistrationsBySalesTypeData";
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_POST_API_PATH = "/addNewLCVRegistrationsBySalesTypeData";
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_DELETE_ALL_API_PATH = "/deleteAllNewLCVRegistrationsBySalesTypeData";

    // 7 - NEW CAR MANUFACTURING
    public static final String NEW_CAR_MANUFACTURING_GET_API_PATH = "/getAllNewCarManufacturingData";
    public static final String NEW_CAR_MANUFACTURING_POST_API_PATH = "/addNewCarManufacturingData";
    public static final String NEW_CAR_MANUFACTURING_DELETE_ALL_API_PATH = "/deleteAllNewCarManufacturingData";

    // 8 - NEW CAR MANUFACTURING BY TYPE
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_GET_API_PATH = "/getAllNewCarManufacturingByTypeData";
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_POST_API_PATH = "/addNewCarManufacturingByTypeData";
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_DELETE_ALL_API_PATH = "/deleteAllNewCarManufacturingByTypeData";

    // 9 - NEW CV MANUFACTURING
    public static final String NEW_CV_MANUFACTURING_GET_API_PATH = "/getAllNewCVManufacturingData";
    public static final String NEW_CV_MANUFACTURING_POST_API_PATH = "/addNewCVManufacturingData";
    public static final String NEW_CV_MANUFACTURING_DELETE_ALL_API_PATH = "/deleteAllNewCVManufacturingData";

    // 10 - NEW CV MANUFACTURING BY TYPE
    public static final String NEW_CV_MANUFACTURING_BY_TYPE_GET_API_PATH = "/getAllNewCVManufacturingByTypeData";
    public static final String NEW_CV_MANUFACTURING_BY_TYPE_POST_API_PATH = "/addNewCVManufacturingByTypeData";
    public static final String NEW_CV_MANUFACTURING_BY_TYPE_DELETE_ALL_API_PATH = "/deleteAllNewCVManufacturingByTypeData";

    // 11 - USED CAR SALES
    public static final String USED_CARS_SALES_GET_API_PATH = "/getAllUsedCarSalesData";
    public static final String USED_CARS_SALES_POST_API_PATH = "/addUsedCarSalesData";
    public static final String USED_CARS_SALES_DELETE_ALL_API_PATH = "/deleteAllUsedCarSalesData";

    // 12 - USED CAR SALES TOP COLORS
    public static final String USED_CARS_TOP_COLORS_SALES_GET_API_PATH = "/getAllUsedCarSalesTopColorsData";
    public static final String USED_CARS_TOP_COLORS_SALES_POST_API_PATH = "/addUsedCarSalesTopColorsData";
    public static final String USED_CARS_TOP_COLORS_SALES_DELETE_ALL_API_PATH = "/deleteAllUsedCarSalesTopColorsData";

    // 13 - USED CAR SALES TOP MODELS
    public static final String USED_CARS_TOP_MODELS_SALES_GET_API_PATH = "/getAllUsedCarSalesTopModelsData";
    public static final String USED_CARS_TOP_MODELS_SALES_POST_API_PATH = "/addUsedCarSalesTopModelsData";
    public static final String USED_CARS_TOP_MODELS_SALES_DELETE_ALL_API_PATH = "/deleteAllUsedCarSalesTopModelData";

    // 14 - USED CAR SALES TOP REGIONS
    public static final String USED_CARS_TOP_REGIONS_SALES_GET_API_PATH = "/getAllUsedCarSalesTopRegionsData";
    public static final String USED_CARS_TOP_REGIONS_SALES_POST_API_PATH = "/addUsedCarSalesTopRegionsData";
    public static final String USED_CARS_TOP_REGIONS_SALES_DELETE_ALL_API_PATH = "/deleteAllUsedCarSalesTopRegionsData";

    // 15 - USER PREFERENCES SEARCH
    public static final String USER_PREFERENCES_SEARCH_GET_API_PATH = "/getUserPreferencesDataByQuery";
    public static final String USER_PREFERENCES_SEARCH_POST_API_PATH = "/addAllUserPreferencesDataByQuery";
    public static final String USER_PREFERENCES_SEARCH_DELETE_ALL_API_PATH = "/deleteAllUserPreferencesDataByQuery";


    // ALL SWAGGER CONSTANTS BELOW ---------------------------------------------------------------------------------------------------------

    // 1 - NEW CAR REGISTRATIONS
    // GET API
    public static final String NEW_CAR_REGISTRATION_GET_SUMMARY = "GET - NEW CAR REGISTRATION DATA";
    public static final String NEW_CAR_REGISTRATION_SUCCESS = "NEW CAR REGISTRATION DATA FETCHED SUCCESSFULLY.";
    public static final String NEW_CAR_REGISTRATION_NO_DATA_FOUND = "NO DATA FOUND FOR NEW CAR REGISTRATION.";
    // GET API BY QUERY
    public static final String NEW_CAR_REGISTRATION_GET_BY_QUERY_SUMMARY = "GET - NEW CAR REGISTRATION DATA";
    public static final String NEW_CAR_REGISTRATION_GET_BY_QUERY_SUCCESS = "NEW CAR REGISTRATION DATA FETCHED SUCCESSFULLY.";
    public static final String NEW_CAR_REGISTRATION_GET_BY_QUERY_NO_DATA_FOUND = "NO DATA FOUND FOR NEW CAR REGISTRATION.";
    // POST API
    public static final String NEW_CAR_REGISTRATION_POST_SUMMARY = "POST - ADD NEW CAR REGISTRATIONS";
    public static final String NEW_CAR_REGISTRATION_ADD_SUCCESS = "NEW CAR REGISTRATIONS DATA ADDED SUCCESSFULLY.";
    public static final String NEW_CAR_REGISTRATION_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING NEW CAR REGISTRATION DATA.";
    // DELETE API
    public static final String NEW_CAR_REGISTRATION_DELETE_ALL_SUMMARY = "DELETE ALL - NEW CAR REGISTRATION DATA";
    public static final String NEW_CAR_REGISTRATION_DELETE_ALL_SUCCESS = "NEW CAR REGISTRATION DATA DELETED SUCCESSFULLY.";
    public static final String NEW_CAR_REGISTRATION_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING NEW CAR REGISTRATION DATA.";

    // 2 - NEW CAR REGISTRATIONS BY FUEL TYPE
    // GET API
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_GET_SUMMARY = "GET - NEW CAR REGISTRATION BY FUEL TYPE DATA";
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_SUCCESS = "NEW CAR REGISTRATION BY FUEL TYPE DATA FETCHED SUCCESSFULLY.";
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_NO_DATA_FOUND = "NO DATA FOUND FOR NEW CAR REGISTRATION BY FUEL TYPE.";
    // POST API
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_POST_SUMMARY = "POST - ADD NEW CAR REGISTRATION BY FUEL TYPE";
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_ADD_SUCCESS = "NEW CAR REGISTRATIONS DATA BY FUEL TYPE ADDED SUCCESSFULLY.";
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING NEW CAR REGISTRATION BY FUEL TYPE DATA.";
    // DELETE API
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_DELETE_ALL_SUMMARY = "DELETE ALL - NEW CAR REGISTRATION BY FUEL TYPE  DATA";
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_DELETE_ALL_SUCCESS = "NEW CAR REGISTRATION BY FUEL TYPE DATA DELETED SUCCESSFULLY.";
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING NEW CAR REGISTRATION BY FUEL TYPE DATA.";

    // 3 - NEW CAR REGISTRATIONS BY SALES TYPE
    // GET API
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_GET_SUMMARY = "GET - NEW CAR REGISTRATION BY SALES TYPE DATA";
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_SUCCESS = "NEW CAR REGISTRATION BY SALES TYPE DATA FETCHED SUCCESSFULLY.";
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_NO_DATA_FOUND = "NO DATA FOUND FOR NEW CAR REGISTRATION BY SALES TYPE.";
    // POST API
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_POST_SUMMARY = "POST - ADD NEW CAR REGISTRATION BY SALES TYPE";
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_ADD_SUCCESS = "NEW CAR REGISTRATIONS DATA BY SALES TYPE ADDED SUCCESSFULLY.";
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING NEW CAR REGISTRATION BY SALES TYPE DATA.";
    // DELETE API
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_DELETE_ALL_SUMMARY = "DELETE ALL - NEW CAR REGISTRATION BY SALES TYPE  DATA";
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_DELETE_ALL_SUCCESS = "NEW CAR REGISTRATION BY SALES TYPE DATA DELETED SUCCESSFULLY.";
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING NEW CAR REGISTRATION BY SALES TYPE DATA.";

    // 4 - NEW LCV REGISTRATIONS
    // GET API
    public static final String NEW_LCV_REGISTRATION_GET_SUMMARY = "GET - NEW LCV REGISTRATION DATA";
    public static final String NEW_LCV_REGISTRATION_SUCCESS = "NEW LCV REGISTRATION DATA FETCHED SUCCESSFULLY.";
    public static final String NEW_LCV_REGISTRATION_NO_DATA_FOUND = "NO DATA FOUND FOR NEW LCV REGISTRATION.";
    // POST API
    public static final String NEW_LCV_REGISTRATION_POST_SUMMARY = "POST - ADD NEW LCV REGISTRATIONS";
    public static final String NEW_LCV_REGISTRATION_ADD_SUCCESS = "NEW LCV REGISTRATIONS DATA ADDED SUCCESSFULLY.";
    public static final String NEW_LCV_REGISTRATION_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING NEW LCV REGISTRATION DATA.";
    // DELETE API
    public static final String NEW_LCV_REGISTRATION_DELETE_ALL_SUMMARY = "DELETE ALL - NEW LCV REGISTRATION DATA";
    public static final String NEW_LCV_REGISTRATION_DELETE_ALL_SUCCESS = "NEW LCV REGISTRATION DATA DELETED SUCCESSFULLY.";
    public static final String NEW_LCV_REGISTRATION_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING NEW LCV REGISTRATION DATA.";

    // 5 - NEW LCV REGISTRATIONS BY FUEL TYPE
    // GET API
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_GET_SUMMARY = "GET - NEW LCV REGISTRATION BY FUEL TYPE DATA";
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_SUCCESS = "NEW LCV REGISTRATION BY FUEL TYPE DATA FETCHED SUCCESSFULLY.";
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_NO_DATA_FOUND = "NO DATA FOUND FOR NEW LCV REGISTRATION BY FUEL TYPE.";
    // POST API
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_POST_SUMMARY = "POST - ADD NEW LCV REGISTRATION BY FUEL TYPE";
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_ADD_SUCCESS = "NEW LCV REGISTRATIONS DATA BY FUEL TYPE ADDED SUCCESSFULLY.";
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING NEW LCV REGISTRATION BY FUEL TYPE DATA.";
    // DELETE API
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_DELETE_ALL_SUMMARY = "DELETE ALL - NEW LCV REGISTRATION BY FUEL TYPE  DATA";
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_DELETE_ALL_SUCCESS = "NEW LCV REGISTRATION BY FUEL TYPE DATA DELETED SUCCESSFULLY.";
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING NEW LCV REGISTRATION BY FUEL TYPE DATA.";


    // 6 - NEW LCV REGISTRATIONS BY SALES TYPE
    // GET API
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_GET_SUMMARY = "GET - NEW LCV REGISTRATION BY SALES TYPE DATA";
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_SUCCESS = "NEW LCV REGISTRATION BY SALES TYPE DATA FETCHED SUCCESSFULLY.";
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_NO_DATA_FOUND = "NO DATA FOUND FOR NEW LCV REGISTRATION BY SALES TYPE.";
    // POST API
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_POST_SUMMARY = "POST - ADD NEW LCV REGISTRATION BY SALES TYPE";
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_ADD_SUCCESS = "NEW LCV REGISTRATIONS DATA BY SALES TYPE ADDED SUCCESSFULLY.";
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING NEW LCV REGISTRATION BY SALES TYPE DATA.";
    // DELETE API
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_DELETE_ALL_SUMMARY = "DELETE ALL - NEW LCV REGISTRATION BY SALES TYPE  DATA";
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_DELETE_ALL_SUCCESS = "NEW LCV REGISTRATION BY SALES TYPE DATA DELETED SUCCESSFULLY.";
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING NEW LCV REGISTRATION BY SALES TYPE DATA.";

    // 7 - NEW CAR MANUFACTURING
    // GET API
    public static final String NEW_CAR_MANUFACTURING_GET_SUMMARY = "GET - NEW CAR MANUFACTURING DATA";
    public static final String NEW_CAR_MANUFACTURING_SUCCESS = "NEW CAR MANUFACTURING DATA FETCHED SUCCESSFULLY.";
    public static final String NEW_CAR_MANUFACTURING_NO_DATA_FOUND = "NO DATA FOUND FOR NEW CAR MANUFACTURING.";
    // POST API
    public static final String NEW_CAR_MANUFACTURING_POST_SUMMARY = "POST - ADD NEW CAR MANUFACTURING";
    public static final String NEW_CAR_MANUFACTURING_ADD_SUCCESS = "NEW CAR MANUFACTURING DATA ADDED SUCCESSFULLY.";
    public static final String NEW_CAR_MANUFACTURING_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING NEW CAR MANUFACTURING DATA.";
    // DELETE API
    public static final String NEW_CAR_MANUFACTURING_DELETE_ALL_SUMMARY = "DELETE ALL - NEW CAR MANUFACTURING DATA";
    public static final String NEW_CAR_MANUFACTURING_DELETE_ALL_SUCCESS = "NEW CAR MANUFACTURING DATA DELETED SUCCESSFULLY.";
    public static final String NEW_CAR_MANUFACTURING_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING NEW CAR MANUFACTURING DATA.";

    // 8 - NEW CAR MANUFACTURING BY TYPE
    // GET API
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_GET_SUMMARY = "GET - NEW CAR MANUFACTURING BY TYPE DATA";
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_SUCCESS = "NEW CAR MANUFACTURING BY TYPE DATA FETCHED SUCCESSFULLY.";
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_NO_DATA_FOUND = "NO DATA FOUND FOR NEW CAR MANUFACTURING BY TYPE.";
    // POST API
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_POST_SUMMARY = "POST - ADD NEW CAR MANUFACTURING BY TYPE";
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_ADD_SUCCESS = "NEW CAR MANUFACTURING DATA BY TYPE ADDED SUCCESSFULLY.";
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING NEW CAR MANUFACTURING BY TYPE DATA.";
    // DELETE API
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_DELETE_ALL_SUMMARY = "DELETE ALL - NEW CAR MANUFACTURING BY TYPE  DATA";
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_DELETE_ALL_SUCCESS = "NEW CAR MANUFACTURING BY TYPE DATA DELETED SUCCESSFULLY.";
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING NEW CAR MANUFACTURING BY TYPE DATA.";

    // 9 - NEW CV MANUFACTURING
    // GET API
    public static final String NEW_CV_MANUFACTURING_GET_SUMMARY = "GET - NEW CV MANUFACTURING DATA";
    public static final String NEW_CV_MANUFACTURING_SUCCESS = "NEW CV MANUFACTURING DATA FETCHED SUCCESSFULLY.";
    public static final String NEW_CV_MANUFACTURING_NO_DATA_FOUND = "NO DATA FOUND FOR NEW CV MANUFACTURING.";
    // POST API
    public static final String NEW_CV_MANUFACTURING_POST_SUMMARY = "POST - ADD NEW CV MANUFACTURING";
    public static final String NEW_CV_MANUFACTURING_ADD_SUCCESS = "NEW CV MANUFACTURING DATA ADDED SUCCESSFULLY.";
    public static final String NEW_CV_MANUFACTURING_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING NEW CV MANUFACTURING DATA.";
    // DELETE API
    public static final String NEW_CV_MANUFACTURING_DELETE_ALL_SUMMARY = "DELETE ALL - NEW CV MANUFACTURING DATA";
    public static final String NEW_CV_MANUFACTURING_DELETE_ALL_SUCCESS = "NEW CV MANUFACTURING DATA DELETED SUCCESSFULLY.";
    public static final String NEW_CV_MANUFACTURING_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING NEW CV MANUFACTURING DATA.";


    // 10 - NEW CV MANUFACTURING BY TYPE
    // GET API
    public static final String NEW_CV_MANUFACTURING_BY_TYPE_GET_SUMMARY = "GET - NEW CV MANUFACTURING BY TYPE DATA";
    public static final String NEW_CV_MANUFACTURING_BY_TYPE_SUCCESS = "NEW CV MANUFACTURING BY TYPE DATA FETCHED SUCCESSFULLY.";
    public static final String NEW_CV_MANUFACTURING_BY_TYPE_NO_DATA_FOUND = "NO DATA FOUND FOR NEW CV MANUFACTURING BY TYPE.";
    // POST API
    public static final String NEW_CV_MANUFACTURING_BY_TYPE_POST_SUMMARY = "POST - ADD NEW CV MANUFACTURING BY TYPE";
    public static final String NEW_CV_MANUFACTURING_BY_TYPE_ADD_SUCCESS = "NEW CV MANUFACTURING DATA BY TYPE ADDED SUCCESSFULLY.";
    public static final String NEW_CV_MANUFACTURING_BY_TYPE_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING NEW CV MANUFACTURING BY TYPE DATA.";
    // DELETE API
    public static final String NEW_CV_MANUFACTURING_BY_TYPE_DELETE_ALL_SUMMARY = "DELETE ALL - NEW CV MANUFACTURING BY TYPE  DATA";
    public static final String NEW_CV_MANUFACTURING_BY_TYPE_DELETE_ALL_SUCCESS = "NEW CV MANUFACTURING BY TYPE DATA DELETED SUCCESSFULLY.";
    public static final String NEW_CV_MANUFACTURING_BY_TYPE_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING NEW CV MANUFACTURING BY TYPE DATA.";


    // 11 - USED CARS SALES
    // GET API
    public static final String USED_CARS_SALES_GET_SUMMARY = "GET - USED CARS SALES DATA";
    public static final String USED_CARS_SALES_SUCCESS = "USED CARS SALES DATA FETCHED SUCCESSFULLY.";
    public static final String USED_CARS_SALES_NO_DATA_FOUND = "NO DATA FOUND FOR USED CARS SALES.";
    // POST API
    public static final String USED_CARS_SALES_POST_SUMMARY = "POST - ADD USED CARS SALES";
    public static final String USED_CARS_SALES_ADD_SUCCESS = "USED CARS SALES DATA ADDED SUCCESSFULLY.";
    public static final String USED_CARS_SALES_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING USED CARS SALES DATA.";
    // DELETE API
    public static final String USED_CARS_SALES_DELETE_ALL_SUMMARY = "DELETE ALL - USED CARS SALES DATA";
    public static final String USED_CARS_SALES_DELETE_ALL_SUCCESS = "USED CARS SALES DATA DELETED SUCCESSFULLY.";
    public static final String USED_CARS_SALES_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING USED CARS SALES DATA.";

    // 12 - USED CARS TOP COLORS SALES
    // GET API
    public static final String USED_CARS_TOP_COLORS_SALES_GET_SUMMARY = "GET - USED CARS TOP COLORS SALES DATA";
    public static final String USED_CARS_TOP_COLORS_SALES_SUCCESS = "USED CARS TOP COLORS SALES DATA FETCHED SUCCESSFULLY.";
    public static final String USED_CARS_TOP_COLORS_SALES_NO_DATA_FOUND = "NO DATA FOUND FOR USED CARS TOP COLORS SALES.";
    // POST API
    public static final String USED_CARS_TOP_COLORS_SALES_POST_SUMMARY = "POST - ADD USED CARS TOP COLORS SALES";
    public static final String USED_CARS_TOP_COLORS_SALES_ADD_SUCCESS = "USED CARS TOP COLORS SALES DATA ADDED SUCCESSFULLY.";
    public static final String USED_CARS_TOP_COLORS_SALES_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING USED CARS TOP COLORS SALES DATA.";
    // DELETE API
    public static final String USED_CARS_TOP_COLORS_SALES_DELETE_ALL_SUMMARY = "DELETE ALL - USED CARS TOP COLORS SALES DATA";
    public static final String USED_CARS_TOP_COLORS_SALES_DELETE_ALL_SUCCESS = "USED CARS TOP COLORS SALES DATA DELETED SUCCESSFULLY.";
    public static final String USED_CARS_TOP_COLORS_SALES_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING USED CARS TOP COLORS SALES DATA.";


    // 13 - USED CARS TOP MODELS SALES
    // GET API
    public static final String USED_CARS_TOP_MODELS_SALES_GET_SUMMARY = "GET - USED CARS TOP MODELS SALES DATA";
    public static final String USED_CARS_TOP_MODELS_SALES_SUCCESS = "USED CARS TOP MODELS SALES DATA FETCHED SUCCESSFULLY.";
    public static final String USED_CARS_TOP_MODELS_SALES_NO_DATA_FOUND = "NO DATA FOUND FOR USED CARS TOP MODELS SALES.";
    // POST API
    public static final String USED_CARS_TOP_MODELS_SALES_POST_SUMMARY = "POST - ADD USED CARS TOP MODELS SALES";
    public static final String USED_CARS_TOP_MODELS_SALES_ADD_SUCCESS = "USED CARS TOP MODELS SALES DATA ADDED SUCCESSFULLY.";
    public static final String USED_CARS_TOP_MODELS_SALES_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING USED CARS TOP MODELS SALES DATA.";
    // DELETE API
    public static final String USED_CARS_TOP_MODELS_SALES_DELETE_ALL_SUMMARY = "DELETE ALL - USED CARS TOP MODELS SALES DATA";
    public static final String USED_CARS_TOP_MODELS_SALES_DELETE_ALL_SUCCESS = "USED CARS TOP MODELS SALES DATA DELETED SUCCESSFULLY.";
    public static final String USED_CARS_TOP_MODELS_SALES_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING USED CARS TOP MODELS SALES DATA.";

    // 14 - USED CARS TOP REGIONS SALES
    // GET API
    public static final String USED_CARS_TOP_REGIONS_SALES_GET_SUMMARY = "GET - USED CARS TOP REGIONS SALES DATA";
    public static final String USED_CARS_TOP_REGIONS_SALES_SUCCESS = "USED CARS TOP REGIONS SALES DATA FETCHED SUCCESSFULLY.";
    public static final String USED_CARS_TOP_REGIONS_SALES_NO_DATA_FOUND = "NO DATA FOUND FOR USED CARS TOP REGIONS SALES.";
    // POST API
    public static final String USED_CARS_TOP_REGIONS_SALES_POST_SUMMARY = "POST - ADD USED CARS TOP REGIONS SALES";
    public static final String USED_CARS_TOP_REGIONS_SALES_ADD_SUCCESS = "USED CARS TOP REGIONS SALES DATA ADDED SUCCESSFULLY.";
    public static final String USED_CARS_TOP_REGIONS_SALES_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING USED CARS TOP REGIONS SALES DATA.";
    // DELETE API
    public static final String USED_CARS_TOP_REGIONS_SALES_DELETE_ALL_SUMMARY = "DELETE ALL - USED CARS TOP REGIONS SALES DATA";
    public static final String USED_CARS_TOP_REGIONS_SALES_DELETE_ALL_SUCCESS = "USED CARS TOP REGIONS SALES DATA DELETED SUCCESSFULLY.";
    public static final String USED_CARS_TOP_REGIONS_SALES_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING USED CARS TOP REGIONS SALES DATA.";

    // 14 - USED CARS TOP REGIONS SALES
    // GET API
    public static final String USER_PREFERENCES_SEARCH_GET_SUMMARY = "GET - USER PREFERENCES DATA";
    public static final String USER_PREFERENCES_SEARCH_SUCCESS = "USER PREFERENCES DATA FETCHED SUCCESSFULLY.";
    public static final String USER_PREFERENCES_SEARCH_NO_DATA_FOUND = "NO DATA FOUND FOR USER PREFERENCES";
    // POST API
    public static final String USER_PREFERENCES_SEARCH_POST_SUMMARY = "POST - USER PREFERENCES DATA";
    public static final String USER_PREFERENCES_SEARCH_ADD_SUCCESS = "USER PREFERENCES DATA ADDED SUCCESSFULLY.";
    public static final String USER_PREFERENCES_SEARCH_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING USER PREFERENCES DATA.";
    // DELETE API
    public static final String USER_PREFERENCES_SEARCH_DELETE_ALL_SUMMARY = "DELETE ALL - USER PREFERENCES DATA";
    public static final String USER_PREFERENCES_SEARCH_DELETE_ALL_SUCCESS = "USER PREFERENCES DATA DELETED SUCCESSFULLY.";
    public static final String USER_PREFERENCES_SEARCH_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING USER PREFERENCES DATA.";

}
